# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# @generated by openapi-python-client. DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast

if TYPE_CHECKING:
  from ..models.circuit_job_settings_error_mitigation_debiasing_type_0_phi_chi_twirling import CircuitJobSettingsErrorMitigationDebiasingType0PhiChiTwirling





T = TypeVar("T", bound="CircuitJobSettingsErrorMitigationDebiasingType0")



@_attrs_define
class CircuitJobSettingsErrorMitigationDebiasingType0:
    """ 
        Attributes:
            phi_chi_twirling (CircuitJobSettingsErrorMitigationDebiasingType0PhiChiTwirling | Unset):
     """

    phi_chi_twirling: CircuitJobSettingsErrorMitigationDebiasingType0PhiChiTwirling | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.circuit_job_settings_error_mitigation_debiasing_type_0_phi_chi_twirling import CircuitJobSettingsErrorMitigationDebiasingType0PhiChiTwirling
        phi_chi_twirling: dict[str, Any] | Unset = UNSET
        if not isinstance(self.phi_chi_twirling, Unset):
            phi_chi_twirling = self.phi_chi_twirling.to_dict()


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
        })
        if phi_chi_twirling is not UNSET:
            field_dict["phi_chi_twirling"] = phi_chi_twirling

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.circuit_job_settings_error_mitigation_debiasing_type_0_phi_chi_twirling import CircuitJobSettingsErrorMitigationDebiasingType0PhiChiTwirling
        d = dict(src_dict)
        _phi_chi_twirling = d.pop("phi_chi_twirling", UNSET)
        phi_chi_twirling: CircuitJobSettingsErrorMitigationDebiasingType0PhiChiTwirling | Unset
        if isinstance(_phi_chi_twirling,  Unset):
            phi_chi_twirling = UNSET
        else:
            phi_chi_twirling = CircuitJobSettingsErrorMitigationDebiasingType0PhiChiTwirling.from_dict(_phi_chi_twirling)




        circuit_job_settings_error_mitigation_debiasing_type_0 = cls(
            phi_chi_twirling=phi_chi_twirling,
        )


        circuit_job_settings_error_mitigation_debiasing_type_0.additional_properties = d
        return circuit_job_settings_error_mitigation_debiasing_type_0

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
