# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# @generated by openapi-python-client. DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.qis_gate import check_qis_gate
from ..models.qis_gate import QisGate
from ..types import UNSET, Unset
from typing import cast






T = TypeVar("T", bound="GateQisGate")



@_attrs_define
class GateQisGate:
    """ 
        Attributes:
            gate (QisGate):
            target (int | Unset):
            targets (list[float] | Unset): The qubits that a quantum gate is applied to
            controls (list[float] | Unset): The qubits that determine whether the operation is applied to targets.
            control (int | Unset):
            rotation (float | Unset): Rotation angle for rx/ry/rz gates
     """

    gate: QisGate
    target: int | Unset = UNSET
    targets: list[float] | Unset = UNSET
    controls: list[float] | Unset = UNSET
    control: int | Unset = UNSET
    rotation: float | Unset = UNSET





    def to_dict(self) -> dict[str, Any]:
        gate: str = self.gate

        target = self.target

        targets: list[float] | Unset = UNSET
        if not isinstance(self.targets, Unset):
            targets = self.targets



        controls: list[float] | Unset = UNSET
        if not isinstance(self.controls, Unset):
            controls = self.controls



        control = self.control

        rotation = self.rotation


        field_dict: dict[str, Any] = {}

        field_dict.update({
            "gate": gate,
        })
        if target is not UNSET:
            field_dict["target"] = target
        if targets is not UNSET:
            field_dict["targets"] = targets
        if controls is not UNSET:
            field_dict["controls"] = controls
        if control is not UNSET:
            field_dict["control"] = control
        if rotation is not UNSET:
            field_dict["rotation"] = rotation

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        gate = check_qis_gate(d.pop("gate"))




        target = d.pop("target", UNSET)

        targets = cast(list[float], d.pop("targets", UNSET))


        controls = cast(list[float], d.pop("controls", UNSET))


        control = d.pop("control", UNSET)

        rotation = d.pop("rotation", UNSET)

        gate_qis_gate = cls(
            gate=gate,
            target=target,
            targets=targets,
            controls=controls,
            control=control,
            rotation=rotation,
        )

        return gate_qis_gate

