# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# @generated by openapi-python-client. DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset






T = TypeVar("T", bound="GetJobEstimateQueryParams")



@_attrs_define
class GetJobEstimateQueryParams:
    """ 
        Attributes:
            backend (str): Available options: `simulator`, `qpu.aria-1`, `qpu.aria-2`, `qpu.forte-1`, `qpu.forte-
                enterprise-1`
            type_ (str | Unset):  Default: 'ionq.circuit.v1'.
            qubits (int | Unset):  Default: 25.
            shots (int | Unset):  Default: 1000.
            field_1q_gates (int | Unset):  Default: 0.
            field_2q_gates (int | Unset):  Default: 0.
            error_mitigation (bool | Unset):  Default: False.
     """

    backend: str
    type_: str | Unset = 'ionq.circuit.v1'
    qubits: int | Unset = 25
    shots: int | Unset = 1000
    field_1q_gates: int | Unset = 0
    field_2q_gates: int | Unset = 0
    error_mitigation: bool | Unset = False





    def to_dict(self) -> dict[str, Any]:
        backend = self.backend

        type_ = self.type_

        qubits = self.qubits

        shots = self.shots

        field_1q_gates = self.field_1q_gates

        field_2q_gates = self.field_2q_gates

        error_mitigation = self.error_mitigation


        field_dict: dict[str, Any] = {}

        field_dict.update({
            "backend": backend,
        })
        if type_ is not UNSET:
            field_dict["type"] = type_
        if qubits is not UNSET:
            field_dict["qubits"] = qubits
        if shots is not UNSET:
            field_dict["shots"] = shots
        if field_1q_gates is not UNSET:
            field_dict["1q_gates"] = field_1q_gates
        if field_2q_gates is not UNSET:
            field_dict["2q_gates"] = field_2q_gates
        if error_mitigation is not UNSET:
            field_dict["error_mitigation"] = error_mitigation

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        backend = d.pop("backend")

        type_ = d.pop("type", UNSET)

        qubits = d.pop("qubits", UNSET)

        shots = d.pop("shots", UNSET)

        field_1q_gates = d.pop("1q_gates", UNSET)

        field_2q_gates = d.pop("2q_gates", UNSET)

        error_mitigation = d.pop("error_mitigation", UNSET)

        get_job_estimate_query_params = cls(
            backend=backend,
            type_=type_,
            qubits=qubits,
            shots=shots,
            field_1q_gates=field_1q_gates,
            field_2q_gates=field_2q_gates,
            error_mitigation=error_mitigation,
        )

        return get_job_estimate_query_params

