# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# @generated by openapi-python-client. DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast

if TYPE_CHECKING:
  from ..models.get_job_estimate_query_params import GetJobEstimateQueryParams
  from ..models.get_job_estimate_response_rate_information import GetJobEstimateResponseRateInformation





T = TypeVar("T", bound="GetJobEstimateResponse")



@_attrs_define
class GetJobEstimateResponse:
    """ 
        Attributes:
            input_values (GetJobEstimateQueryParams):
            estimated_at (str):
            cost_unit (str):
            rate_information (GetJobEstimateResponseRateInformation):
            estimated_cost (float):
            estimated_execution_time (float):
            current_predicted_queue_time (float):
     """

    input_values: GetJobEstimateQueryParams
    estimated_at: str
    cost_unit: str
    rate_information: GetJobEstimateResponseRateInformation
    estimated_cost: float
    estimated_execution_time: float
    current_predicted_queue_time: float





    def to_dict(self) -> dict[str, Any]:
        from ..models.get_job_estimate_query_params import GetJobEstimateQueryParams
        from ..models.get_job_estimate_response_rate_information import GetJobEstimateResponseRateInformation
        input_values = self.input_values.to_dict()

        estimated_at = self.estimated_at

        cost_unit = self.cost_unit

        rate_information = self.rate_information.to_dict()

        estimated_cost = self.estimated_cost

        estimated_execution_time = self.estimated_execution_time

        current_predicted_queue_time = self.current_predicted_queue_time


        field_dict: dict[str, Any] = {}

        field_dict.update({
            "input_values": input_values,
            "estimated_at": estimated_at,
            "cost_unit": cost_unit,
            "rate_information": rate_information,
            "estimated_cost": estimated_cost,
            "estimated_execution_time": estimated_execution_time,
            "current_predicted_queue_time": current_predicted_queue_time,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.get_job_estimate_query_params import GetJobEstimateQueryParams
        from ..models.get_job_estimate_response_rate_information import GetJobEstimateResponseRateInformation
        d = dict(src_dict)
        input_values = GetJobEstimateQueryParams.from_dict(d.pop("input_values"))




        estimated_at = d.pop("estimated_at")

        cost_unit = d.pop("cost_unit")

        rate_information = GetJobEstimateResponseRateInformation.from_dict(d.pop("rate_information"))




        estimated_cost = d.pop("estimated_cost")

        estimated_execution_time = d.pop("estimated_execution_time")

        current_predicted_queue_time = d.pop("current_predicted_queue_time")

        get_job_estimate_response = cls(
            input_values=input_values,
            estimated_at=estimated_at,
            cost_unit=cost_unit,
            rate_information=rate_information,
            estimated_cost=estimated_cost,
            estimated_execution_time=estimated_execution_time,
            current_predicted_queue_time=current_predicted_queue_time,
        )

        return get_job_estimate_response

