# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by openapi-python-client. DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast

if TYPE_CHECKING:
  from ..models.hamiltonian_energy_input_data import HamiltonianEnergyInputData





T = TypeVar("T", bound="HamiltonianEnergyInput")



@_attrs_define
class HamiltonianEnergyInput:
    """ 
        Attributes:
            data (HamiltonianEnergyInputData):
            params (list[float] | Unset):
     """

    data: HamiltonianEnergyInputData
    params: list[float] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.hamiltonian_energy_input_data import HamiltonianEnergyInputData
        data = self.data.to_dict()

        params: list[float] | Unset = UNSET
        if not isinstance(self.params, Unset):
            params = self.params




        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "data": data,
        })
        if params is not UNSET:
            field_dict["params"] = params

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.hamiltonian_energy_input_data import HamiltonianEnergyInputData
        d = dict(src_dict)
        data = HamiltonianEnergyInputData.from_dict(d.pop("data"))




        params = cast(list[float], d.pop("params", UNSET))


        hamiltonian_energy_input = cls(
            data=data,
            params=params,
        )


        hamiltonian_energy_input.additional_properties = d
        return hamiltonian_energy_input

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
