# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by openapi-python-client. DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset







T = TypeVar("T", bound="HamiltonianPauliTerm")



@_attrs_define
class HamiltonianPauliTerm:
    """ 
        Attributes:
            pauli_string (str):
            coefficient (float):
     """

    pauli_string: str
    coefficient: float
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        pauli_string = self.pauli_string

        coefficient = self.coefficient


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "pauli_string": pauli_string,
            "coefficient": coefficient,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        pauli_string = d.pop("pauli_string")

        coefficient = d.pop("coefficient")

        hamiltonian_pauli_term = cls(
            pauli_string=pauli_string,
            coefficient=coefficient,
        )


        hamiltonian_pauli_term.additional_properties = d
        return hamiltonian_pauli_term

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
