# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# @generated by openapi-python-client

from typing import Literal, cast

HamiltonianEnergyInputDataType = Literal['hamiltonian-energy']

HAMILTONIAN_ENERGY_INPUT_DATA_TYPE_VALUES: set[HamiltonianEnergyInputDataType] = { 'hamiltonian-energy',  }

def check_hamiltonian_energy_input_data_type(value: str) -> HamiltonianEnergyInputDataType:
    if value in HAMILTONIAN_ENERGY_INPUT_DATA_TYPE_VALUES:
        return cast(HamiltonianEnergyInputDataType, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {HAMILTONIAN_ENERGY_INPUT_DATA_TYPE_VALUES!r}")
