# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# @generated by openapi-python-client

from typing import Literal, cast

JobsDeletedResponseStatus = Literal['deleted']

JOBS_DELETED_RESPONSE_STATUS_VALUES: set[JobsDeletedResponseStatus] = { 'deleted',  }

def check_jobs_deleted_response_status(value: str) -> JobsDeletedResponseStatus:
    if value in JOBS_DELETED_RESPONSE_STATUS_VALUES:
        return cast(JobsDeletedResponseStatus, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {JOBS_DELETED_RESPONSE_STATUS_VALUES!r}")
