# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by openapi-python-client. DO NOT EDIT.

from typing import Literal, cast

JSONMultiCircuitJobType = Literal['ionq.multi-circuit.v1']

JSON_MULTI_CIRCUIT_JOB_TYPE_VALUES: set[JSONMultiCircuitJobType] = { 'ionq.multi-circuit.v1',  }

def check_json_multi_circuit_job_type(value: str) -> JSONMultiCircuitJobType:
    if value in JSON_MULTI_CIRCUIT_JOB_TYPE_VALUES:
        return cast(JSONMultiCircuitJobType, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {JSON_MULTI_CIRCUIT_JOB_TYPE_VALUES!r}")
