# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by openapi-python-client. DO NOT EDIT.

from typing import Literal, cast

SessionStatusEnum = Literal['created', 'ended', 'started']

SESSION_STATUS_ENUM_VALUES: set[SessionStatusEnum] = { 'created', 'ended', 'started',  }

def check_session_status_enum(value: str) -> SessionStatusEnum:
    if value in SESSION_STATUS_ENUM_VALUES:
        return cast(SessionStatusEnum, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {SESSION_STATUS_ENUM_VALUES!r}")
