# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# @generated by openapi-python-client

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from dateutil.parser import isoparse
from typing import cast
import datetime

if TYPE_CHECKING:
  from ..models.group_usage import GroupUsage





T = TypeVar("T", bound="Usage")



@_attrs_define
class Usage:
    """ Single date of QPU usage

        Attributes:
            amount (float): The amount as a cost in USD Example: 1614.23.
            from_ (datetime.date): Date for this group's usage Example: 2023-07-01.
            group_usages (list[GroupUsage]): The top 5 usage groups in order of cost amount descending
            job_count (int): The count of jobs for this group on the given from date Example: 10.
            time_us (float): The QPU time in microseconds Example: 5143166.13413.
     """

    amount: float
    from_: datetime.date
    group_usages: list[GroupUsage]
    job_count: int
    time_us: float
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.group_usage import GroupUsage
        amount = self.amount

        from_ = self.from_.isoformat()

        group_usages = []
        for group_usages_item_data in self.group_usages:
            group_usages_item = group_usages_item_data.to_dict()
            group_usages.append(group_usages_item)



        job_count = self.job_count

        time_us = self.time_us


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "amount": amount,
            "from": from_,
            "group_usages": group_usages,
            "job_count": job_count,
            "time_us": time_us,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.group_usage import GroupUsage
        d = dict(src_dict)
        amount = d.pop("amount")

        from_ = isoparse(d.pop("from")).date()




        group_usages = []
        _group_usages = d.pop("group_usages")
        for group_usages_item_data in (_group_usages):
            group_usages_item = GroupUsage.from_dict(group_usages_item_data)



            group_usages.append(group_usages_item)


        job_count = d.pop("job_count")

        time_us = d.pop("time_us")

        usage = cls(
            amount=amount,
            from_=from_,
            group_usages=group_usages,
            job_count=job_count,
            time_us=time_us,
        )


        usage.additional_properties = d
        return usage

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
