# Copyright 2026 IonQ, Inc.
# SPDX-License-Identifier: Apache-2.0
# AUTO-GENERATED by openapi-python-client. DO NOT EDIT.

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.get_characterizations_for_backend_backend import check_get_characterizations_for_backend_backend
from ...models.get_characterizations_for_backend_backend import GetCharacterizationsForBackendBackend
from ...models.get_characterizations_for_backend_response_200 import GetCharacterizationsForBackendResponse200
from ...types import UNSET, Unset
from typing import cast



def _get_kwargs(
    backend: GetCharacterizationsForBackendBackend,
    *,
    start: str | Unset = UNSET,
    end: str | Unset = UNSET,
    limit: int | Unset = 10,
    page: int | Unset = UNSET,

) -> dict[str, Any]:
    

    

    params: dict[str, Any] = {}

    params["start"] = start

    params["end"] = end

    params["limit"] = limit

    params["page"] = page


    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}


    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/backends/{backend}/characterizations".format(backend=quote(str(backend), safe=""),),
        "params": params,
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> GetCharacterizationsForBackendResponse200 | None:
    if response.status_code == 200:
        response_200 = GetCharacterizationsForBackendResponse200.from_dict(response.json())



        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[GetCharacterizationsForBackendResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    backend: GetCharacterizationsForBackendBackend,
    *,
    client: AuthenticatedClient | Client,
    start: str | Unset = UNSET,
    end: str | Unset = UNSET,
    limit: int | Unset = 10,
    page: int | Unset = UNSET,

) -> Response[GetCharacterizationsForBackendResponse200]:
    """ Get All Backend Characterizations

     This endpoint retrieves an array of all available backend characterizations, with pagination.

    Args:
        backend (GetCharacterizationsForBackendBackend):
        start (str | Unset):
        end (str | Unset):
        limit (int | Unset):  Default: 10.
        page (int | Unset): Specify the page of results to return.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[GetCharacterizationsForBackendResponse200]
     """


    kwargs = _get_kwargs(
        backend=backend,
start=start,
end=end,
limit=limit,
page=page,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    backend: GetCharacterizationsForBackendBackend,
    *,
    client: AuthenticatedClient | Client,
    start: str | Unset = UNSET,
    end: str | Unset = UNSET,
    limit: int | Unset = 10,
    page: int | Unset = UNSET,

) -> GetCharacterizationsForBackendResponse200 | None:
    """ Get All Backend Characterizations

     This endpoint retrieves an array of all available backend characterizations, with pagination.

    Args:
        backend (GetCharacterizationsForBackendBackend):
        start (str | Unset):
        end (str | Unset):
        limit (int | Unset):  Default: 10.
        page (int | Unset): Specify the page of results to return.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        GetCharacterizationsForBackendResponse200
     """


    return sync_detailed(
        backend=backend,
client=client,
start=start,
end=end,
limit=limit,
page=page,

    ).parsed

async def asyncio_detailed(
    backend: GetCharacterizationsForBackendBackend,
    *,
    client: AuthenticatedClient | Client,
    start: str | Unset = UNSET,
    end: str | Unset = UNSET,
    limit: int | Unset = 10,
    page: int | Unset = UNSET,

) -> Response[GetCharacterizationsForBackendResponse200]:
    """ Get All Backend Characterizations

     This endpoint retrieves an array of all available backend characterizations, with pagination.

    Args:
        backend (GetCharacterizationsForBackendBackend):
        start (str | Unset):
        end (str | Unset):
        limit (int | Unset):  Default: 10.
        page (int | Unset): Specify the page of results to return.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[GetCharacterizationsForBackendResponse200]
     """


    kwargs = _get_kwargs(
        backend=backend,
start=start,
end=end,
limit=limit,
page=page,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    backend: GetCharacterizationsForBackendBackend,
    *,
    client: AuthenticatedClient | Client,
    start: str | Unset = UNSET,
    end: str | Unset = UNSET,
    limit: int | Unset = 10,
    page: int | Unset = UNSET,

) -> GetCharacterizationsForBackendResponse200 | None:
    """ Get All Backend Characterizations

     This endpoint retrieves an array of all available backend characterizations, with pagination.

    Args:
        backend (GetCharacterizationsForBackendBackend):
        start (str | Unset):
        end (str | Unset):
        limit (int | Unset):  Default: 10.
        page (int | Unset): Specify the page of results to return.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        GetCharacterizationsForBackendResponse200
     """


    return (await asyncio_detailed(
        backend=backend,
client=client,
start=start,
end=end,
limit=limit,
page=page,

    )).parsed
